# Generated by Django 5.0.6 on 2024-05-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleLemon', '0003_drinkscategory_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demoformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reserv_date', models.DateField()),
            ],
        ),
    ]
